language: python

services:
  - docker

install:
  - sudo pip install docker-compose

script:
  - docker pull mysql:5.7.14
  - docker pull haproxy:1.7
  - mkdir -p ~/cs4501/app
  - mkdir -p ~/cs4501/db
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
  - docker ps -a
#  - docker build haproxy:1.7
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.17 bash
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.17 bash -c "echo 'drop user '\''www'\''@'\''%'\'';create user '\''www'\''@'\''%'\'' identified by '\''\$3cureUS'\'';drop database cs4501;create database cs4501 character set utf8;grant all on cs4501.* to '\''www'\''@'\''%'\'';' > createUser.sql && cat createUser.sql && mysql -uroot -p'\$3cureUS' -h db < createUser.sql"
  - mysql -uroot -p'$3cureUS' -h db
  - create user 'www'@'%' identified by '$3cureUS';
  - create database cs4501 character set utf8;
  - grant all on cs4501.* to 'www'@'%';
  - ^D
  - ^Z
  - docker cp ./createUser.sql mysql-cmdline:/
  - docker exec mysql-cmdline bash -c "mysql -uroot -p'$3cureUS' -h db < /createUser.sql" 
  - docker-compose up -d
  - docker ps -a
  - sleep 200
  - docker exec models_layer bash -c "python manage.py test"
  - docker ps -a
#  - pip install selenium
#  - WEB_APP_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' haproxy)
#  - SELENIUM_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' selenium)
#  - python unitTestSel.py ${SELENIUM_IP} ${WEB_APP_IP}

notifications:
  emails:
    - bhc9av@virginia.edu
