models:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./Microservices\ API:/app
    ports:
      - "8001:8000"
    command: bash -c "./Microservices\ API/manage.py makemigrations api; python ./Microservices\ API/manage.py makemigrations; python ./Microservices\ API/manage.py migrate; python ./Microservices\ API/manage.py loaddata ./Microservices\ API/db.json; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/Microservices\ API/bakery/wsgi.py"

exp:
   image: tp33/django
   links:
      - models:models-api
   ports:
      - "8002:8000"
   volumes:
      - ./expservice:/app
   command: bash -c "./expservice/manage.py makemigrations api; python ./expservice/manage.py makemigrations; python ./expservice/manage.py migrate; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/expservice/services/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8000:8000"
   volumes:
      - ./BakeryWebsite:/app
   command: bash -c "./BakeryWebsite/manage.py makemigrations api; python ./BakeryWebsite/manage.py makemigrations; python ./BakeryWebsite/manage.py \
migrate; mod_wsgi-express start-server --working-directory /app --reload-on-changes /app/BakeryWebsite/bakery/wsgi.py"